# Generated by Django 5.2.17 on 2026-09-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('raw_response', models.TextField()),
                ('normalized_response', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_queries', to='chats.chat')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FinalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('synthesis_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_response', to='research.researchquery')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('source_name', models.CharField(max_length=200)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('agent_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='research.agentresponse')),
                ('research_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='research.researchquery')),
            ],
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='research_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_responses', to='research.researchquery'),
        ),
    ]
