# Generated by Django 5.2.17 on 2026-09-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponse',
            name='citations_used',
            field=models.ManyToManyField(blank=True, related_name='evidence_attempts', to='research.citation'),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='cost_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='input_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='latency_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='output_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='paper_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='provider_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='succeeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='total_tokens',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='evaluation_case',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='total_duration_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SynthesisAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('cost_source', models.CharField(blank=True, max_length=20)),
                ('succeeded', models.BooleanField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=200)),
                ('answer', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('synthesis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthesis_attempts', to='research.researchquery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='finalresponse',
            name='active_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.synthesisattempt'),
        ),
    ]
