# Generated by Django 5.2.17 on 2026-09-20 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_preserve_existing_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquery',
            name='execution_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='execution_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='stage',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='researchquery',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DeveloperRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('citation_quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('evidence_relevance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('synthesis_quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='research.researchquery')),
                ('synthesis_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.synthesisattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(unique=True)),
                ('target', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='research.researchquery')),
            ],
        ),
    ]
